# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nv < Formula
  desc "Lightweight utility to load context specific environment variables"
  homepage "https://github.com/jcouture/nv"
  version "2.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jcouture/nv/releases/download/2.2.0/nv_2.2.0_darwin_arm64.tar.gz"
      sha256 "abbf4d537479c09b36bf13b937bbab6ffc2913d89cb03819fe77367731b3db84"

      def install
        bin.install "nv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jcouture/nv/releases/download/2.2.0/nv_2.2.0_darwin_amd64.tar.gz"
      sha256 "4878190db337b586a919f0936409b8afb2e784f0a1179027704860431a10ba1d"

      def install
        bin.install "nv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jcouture/nv/releases/download/2.2.0/nv_2.2.0_linux_armv6.tar.gz"
      sha256 "a58c1799c7dbd37e059fdd4714e9f7dcd56ded464080fa6d092bb940ceda9d95"

      def install
        bin.install "nv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jcouture/nv/releases/download/2.2.0/nv_2.2.0_linux_amd64.tar.gz"
      sha256 "38920f840cf709cbb5d1cdbdffbae3e4d3937a70dc30564b409932ccb2d36cb1"

      def install
        bin.install "nv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcouture/nv/releases/download/2.2.0/nv_2.2.0_linux_arm64.tar.gz"
      sha256 "ce8d85fd7299ab29758202e7902a7b7eb8bbfd8d64461aa189e2722796aa5f3e"

      def install
        bin.install "nv"
      end
    end
  end

  test do
    system "#{bin}/nv"
  end
end
