# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nv < Formula
  desc "Lightweight utility to load context specific environment variables"
  homepage "https://github.com/jcouture/nv"
  version "2.2.4"

  on_macos do
    on_intel do
      url "https://github.com/jcouture/nv/releases/download/2.2.4/nv_2.2.4_darwin_amd64.tar.gz"
      sha256 "ba938c0075f46e93650190992d9f127d9254469ea31a55d1fd288d2ab34f9f87"

      def install
        bin.install "nv"
      end
    end
    on_arm do
      url "https://github.com/jcouture/nv/releases/download/2.2.4/nv_2.2.4_darwin_arm64.tar.gz"
      sha256 "8125cc88e4d16d8d3ed5aabd11f54c13f11b04577c79a2a5f8c85fa3d430e58d"

      def install
        bin.install "nv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jcouture/nv/releases/download/2.2.4/nv_2.2.4_linux_amd64.tar.gz"
        sha256 "18d610db20eeeaa468cca301d387dc94448253f6837300ecb480fac8ae7c06da"

        def install
          bin.install "nv"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/jcouture/nv/releases/download/2.2.4/nv_2.2.4_linux_armv6.tar.gz"
        sha256 "6346920134cbc11801bad349a9f0f563a319c48a02e569bedd4391e7012c633b"

        def install
          bin.install "nv"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jcouture/nv/releases/download/2.2.4/nv_2.2.4_linux_arm64.tar.gz"
        sha256 "f0e37f11469be4c5658abd5e772a55cf4fcff0991a5e6844f7193c22b318a46d"

        def install
          bin.install "nv"
        end
      end
    end
  end

  deprecate! date: "2026-06-24", because: "has moved to a cask on jcouture/tap", replacement_cask: "jcouture/tap/nv"

  test do
    system "#{bin}/nv"
  end
end
